apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-helloworld
spec:
  containers:
    - name: helloworld-app
      image: {{.Values.helloworld.image.name}}:{{.Chart.AppVersion}}
      ports:
        - containerPort: 3000
      env:
        - name: ARGOCD_BRANCHES_APP_ENV
          value: {{.Values.helloworld.environment}}