apiVersion: v1
kind: Pod
metadata:
  name: helloworld-app-{{.Release.Revision}}
  namespace: test
spec:
  containers:
    - name: helloworld-app
      image: {{.Values.helloworld.image.name}}:{{.Chart.AppVersion}}
      ports:
        - containerPort: 3000