apiVersion: v1
kind: Pod
metadata:
  generateName: helloworld-app-
spec:
  containers:
    - name: helloworld-app
      image: {{.Values.helloworld.image.name}}:{{.Values.helloworld.image.version}}
      ports:
        - containerPort: 3000